module Euler
  module Math
    type numeric = Integer | Complex | Float

    def self.rng_seed=: (Integer) -> void
    def self.rng_seed: () -> Integer

    def self.abs: () -> void
    def self.accu: () -> void
    def self.all: () -> void
    def self.any: () -> void
    def self.approx_equal: () -> void
    def self.arg: () -> void
    def self.as_scalar: () -> void
    def self.balance: () -> void
    def self.circshift: () -> void
    def self.clamp: () -> void
    def self.cond: () -> void
    def self.conj: () -> void
    def self.conv_to: () -> void
    def self.cross: () -> void
    def self.cumsum: () -> void
    def self.cumprod: () -> void
    def self.det: () -> void
    def self.diagmat: () -> void
    def self.diagvec: () -> void
    def self.diags: () -> void
    def self.spdiags: () -> void
    def self.diff: () -> void
    def self.dot: () -> void
    def self.cdot: () -> void
    def self.norm_dot: () -> void
    def self.eps: () -> void
    def self.expmat: () -> void
    def self.expmat_sym: () -> void
    def self.find: () -> void
    def self.find_finite: () -> void
    def self.find_nonfinite: () -> void
    def self.find_nan: () -> void
    def self.find_nonnan: () -> void
    def self.find_unique: () -> void
    def self.fliplr: () -> void
    def self.flipud: () -> void
    def self.imag: () -> void
    def self.real: () -> void
    def self.ind2sub: () -> void
    def self.index_min: () -> void
    def self.index_max: () -> void
    def self.inplace_trans: () -> void
    def self.intersect: () -> void
    def self.join_rows: () -> void
    def self.join_cols: () -> void
    def self.join_slices: () -> void
    def self.kron: () -> void
    def self.log_det: () -> void
    def self.log_det_sympd: () -> void
    def self.logmat: () -> void
    def self.logmat_sympd: () -> void
    def self.min: () -> void
    def self.max: () -> void
    def self.norm: () -> void
    def self.norm2est: () -> void
    def self.normalise: () -> void
    def self.nonzeros: () -> void
    def self.omit_nan: () -> void
    def self.omit_nonfinite: () -> void
    def self.pow: () -> void
    def self.powmat: () -> void
    def self.prod: () -> void
    def self.rank: () -> void
    def self.rcond: () -> void
    def self.repelem: () -> void
    def self.replace: () -> void
    def self.repmat: () -> void
    def self.repcube: () -> void
    def self.reshape: () -> void
    def self.resize: () -> void
    def self.reverse: () -> void
    def self.roots: () -> void
    def self.shuffle: () -> void
    def self.size: () -> void
    def self.sort: () -> void
    def self.sort_index: () -> void
    def self.sqrtmat: () -> void
    def self.sqrtmat_sympd: () -> void
    def self.sum: () -> void
    def self.sub2ind: () -> void
    def self.symmatu: () -> void
    def self.symmatl: () -> void
    def self.trace: () -> void
    def self.trans: () -> void
    def self.trapz: () -> void
    def self.trimatu: () -> void
    def self.trimatl: () -> void
    def self.trimatu_ind: () -> void
    def self.trimatl_ind: () -> void
    def self.unique: () -> void
    def self.vecnorm: () -> void
    def self.vectorise: () -> void
    def self.exp: () -> void
    def self.log: () -> void
    def self.square: () -> void
    def self.floor: () -> void
    def self.erf: () -> void
    def self.tgamma: () -> void
    def self.sign: () -> void
    def self.exp2: () -> void
    def self.log2: () -> void
    def self.sqrt: () -> void
    def self.ceil: () -> void
    def self.erfc: () -> void
    def self.lgamma: () -> void
    def self.exp10: () -> void
    def self.log10: () -> void
    def self.cbrt: () -> void
    def self.round: () -> void
    def self.expm1: () -> void
    def self.log1p: () -> void
    def self.trunc: () -> void
    def self.trunc_exp: () -> void
    def self.trunc_log: () -> void
    def self.cos: () -> void
    def self.acos: () -> void
    def self.cosh: () -> void
    def self.acosh: () -> void
    def self.sin: () -> void
    def self.asin: () -> void
    def self.sinh: () -> void
    def self.asinh: () -> void
    def self.tan: () -> void
    def self.atan: () -> void
    def self.tanh: () -> void
    def self.atanh: () -> void
    def self.sinc: () -> void
    def self.atan2: () -> void
    def self.hypot: () -> void
    def self.chol: () -> void
    def self.eig_sym: () -> void
    def self.eig_gen: () -> void
    def self.eig_pair: () -> void
    def self.hess: () -> void
    def self.inv: () -> void
    def self.inv_sympd: () -> void
    def self.lu: () -> void
    def self.null: () -> void
    def self.orth: () -> void
    def self.pinv: () -> void
    def self.qr: () -> void
    def self.qr_econ: () -> void
    def self.qz: () -> void
    def self.schur: () -> void
    def self.solve: () -> void
    def self.svd: () -> void
    def self.svd_econ: () -> void
    def self.sylvester: () -> void
    def self.eigs_sym: () -> void
    def self.eigs_gen: () -> void
    def self.svds: () -> void
    def self.spsolve: () -> void
    def self.spsolve_factorizer: () -> void
    def self.affmul: () -> void
    def self.conv: () -> void
    def self.conv2: () -> void
    def self.fft: () -> void
    def self.ifft: () -> void
    def self.fft2: () -> void
    def self.ifft2: () -> void
    def self.interp1: () -> void
    def self.interp2: () -> void
    def self.polyfit: () -> void
    def self.polyval: () -> void
    def self.mean: () -> void
    def self.median: () -> void
    def self.stddev: () -> void
    def self.var: () -> void
    def self.range: () -> void
    def self.cov: () -> void
    def self.cor: () -> void
    def self.hist: () -> void
    def self.histc: () -> void
    def self.quantile: () -> void
    def self.princomp: () -> void
    def self.normpdf: () -> void
    def self.log_normpdf: () -> void
    def self.normcdf: () -> void
    def self.mvnrnd: () -> void
    def self.chi2rnd: () -> void
    def self.wishrnd: () -> void
    def self.iwishrnd: () -> void
    def self.running_stat: () -> void
    def self.running_stat_vec: () -> void
    def self.kmeans: () -> void
    def self.gmm_diag: () -> void
    def self.gmm_full: () -> void
    def self.set_rng_seed: () -> void
    def self.set_rng_seed_random: () -> void


  end
end